### ISSUE TITLE
#847 Cloud transient model,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#847] opened 2016-09-28 22:05 UTC
This ticket tracks the development of the UVic solar cloud transient model.,

**Comment by afisher1** [comment] 2017-03-17 22:23
@dchassin what is the status of this issue?

**Comment by dchassin** [comment] 2017-03-18 16:12
I think this ticket has be superseded by the cloud transients implemented based on NREL's model.  The only thing that may be missing from the NREL model is the PV pre/post surge we observe in the data collected from http://www.victoriaweather.ca/. The surges can be quite significant and increase the magnitude of the total transient by as much 30% depending on the cloud type.  It may make sense to open a new ticket to address this remaining issue using the existing cloud transient code.

**Comment by dchassin** [comment] 2017-03-18 16:38
A specific example of surge effect can be observed at [Victoria Weather/UVic Science/7 July 2014/Insolation](http://www.victoriaweather.ca/data.php?field=insolation&id=143&year=2014&month=07&day=07). The event is caused by bright departing clouds.  The aspect view of the clouds is high enough and they are bright enough relative to clear sky that it increases the output of the panel by as much as 15%.

**Comment by trevorhardy** [comment] 2022-05-10 16:54
Closing for now as the core cloud-cover functionality has been incorporated though it is lacking the sun-surge effect @dchassin has mentioned.

**Closed by trevorhardy** 2022-05-10 16:54 UTC
Labels: enhancement
