### ISSUE TITLE
Inconsistency between house total_load and hvac_load 

### ISSUE THREAD

**Issue by laurmarinovici** [gridlab-d/gridlab-d#1249] opened 2020-05-29 19:44 UTC
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
House total_load < House hvac_load when HVAC on, which lead to negative values for the ZIP load attached to the house, which is calculated as 

      ZIP load = total_load - hvac_load.
## Please provide the steps to reproduce.
Simply run the attached GLM to record the data, then analyze the data as in the graphs attached.

## If possible, please provide any screenshots and other supporting information.

![total_VS_hvac_loads](https://user-images.githubusercontent.com/6537831/83296892-63d88a00-a1a6-11ea-8d6b-1354ef476c45.png)

[Archive.zip](https://github.com/gridlab-d/gridlab-d/files/4703940/Archive.zip)

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment] 2020-06-01 15:24
Some early thoughts were that this may be a circuit breaker issue, similar to those (or an extension of) issue #1213.  Still needs to be confirmed, but documenting here for tracking.

**Comment by ftuffner** [comment] 2020-06-04 23:58
Initial testing seems to confirm it is related to the breaker tripping, but the system still proceeding.  Not as obvious sometimes in this file, due to the odd recorder intervals (HVAC can click online and trip during intermediate times).  If `hvac_breaker_rating` is set to something higher (like 500 A), it seems to work fine.

So basically appears to be the same fundamental issue as #1213, but expressing it in a different manner.

**Comment by ftuffner** [comment] 2020-06-19 21:42
Fix of PR #1250 appears to have worked, so closing this.

**Closed by ftuffner** 2020-06-19 21:42 UTC
Labels: Priority: Major
