### ISSUE TITLE
Modify helics_msg to use the HELICS 2.0 API 

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1153] opened 2018-10-26 17:09 UTC
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
This is an enhancement to the current helics_msg object such that it will use the 2.0 version of the HELICS API 

## Please provide the steps to reproduce.
NA

## Please provide the exact error/warnining/failure message printed on the console.
NA

## If possible, please provide any screenshots and other supporting information.
NA

-------------------------------------------------------------------------------------------------------------

**Comment by kdheepak** [comment] 2019-02-14 22:21
What's the status of this issue?

**Comment by kdheepak** [comment] 2019-03-07 19:57
@afisher1 I think you should consider using the C98 interface in GridLAB-D. See this folder for reference.

https://github.com/GMLC-TDC/HELICS-src/tree/master/src/helics/cpp98

This is a header only implementation of the HELICS interface that uses the C interface. This separates the implementation of HELICS (and their dependencies) from the interface that HELICS exposes (optional: See [this talk](https://www.youtube.com/watch?v=PVYdHDm0q6Y)  on hour glass interfaces for reference).

If you use this and link with HELICS as a dynamic library, then users can compile GridLAB-D with GCC but use pre-compiled binaries of HELICS and its dependencies from clang.

The advantage of this is that if a user wants to install HELICS for GridLAB-D and if the user needs to compile GridLAB-D from source, then the user will not need to compile HELICS, ZeroMQ and Boost from source using GCC as well. They can just type `conda install -c gmlc-tdc helics` and everything should work. This will avoid issues like [this](https://github.com/GMLC-TDC/HELICS-src/issues/641) in the future if Boost / ZMQ change in any way.

cc @temcdrm @phlptp @nightlark for additional comments.

**Comment by phlptp** [comment] 2019-03-07 20:46
I would support that,  My guess is the cpp98 interface needs a little loving care to make sure the duplicate capabilities are there but that is what it was intended for.  C++ applications that for one reason were not updated to the same standard or wanted an optional component.    GridLab-d seems like a good candidate for that.  I actually think NS-3 would have an easier time doing the same thing as well.

**Comment by ftuffner** [comment] 2022-01-31 20:50
v4.3 compiles with HELICSv.2.7.x, so assuming this was fixed as part of that.  Closing as part of ticket cleanup.

**Closed by ftuffner** 2022-01-31 20:50 UTC
Labels: enhancement
