### ISSUE TITLE
Failure to read player files when different time zone are specified in the .glm and player files 

### ISSUE THREAD

**Issue by BilalAhmad-Bhatti** [gridlab-d/gridlab-d#1332] opened 2022-03-17 19:41 UTC
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
During testing of wind speed player files, it was found that GridLAB-D fails to read data from the player file when there are different time zones specified in .glm and player files. Currently, it seems like the only workaround is defining the same time zones in both .glm and .player files.

## Please provide the steps to reproduce.
Use different time zones in .glm and .player files.

## Please provide the exact error/warnining/failure message printed on the console.
ERROR: sync_player:22: not enough values on line:
ERROR: [timestamp] object player:22 stopped its clock (exec) !

## If possible, please provide any screenshots and other supporting information.
![image](https://user-images.githubusercontent.com/77303091/158882583-b5f00191-666a-4745-873d-cefd27d96d30.png)

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment] 2022-04-02 00:23
Despite initial thoughts, mkdatetime in timestamp.c only checks to see if the TZ is GMT or the specified one (or its DST variant).  If it doesn't match, it fails out.  Contemplating if this is "by design and acceptable", or if we should make it so it automatically offsets things (with a warning, of course).

**Comment by dchassin** [comment] 2022-04-02 05:28
It was by design. But this is something that was addressed somewhat obliquely in HiPAS by supporting ISO timestamps. If you want I can copy the fix from there.

**Comment by trevorhardy** [comment] 2022-08-24 23:21
Assuming we get to do our big "tape" module re-write, this could be addressed more fully. For now, I'm closing this out as "by design and acceptable".

**Closed by trevorhardy** 2022-08-24 23:21 UTC
Labels: bug
