### ISSUE TITLE
Autotests not consistent in failure code

### ISSUE THREAD

**Issue by jcfuller1** [gridlab-d/gridlab-d#1011] opened 2017-02-14 17:25 UTC
From an email message:

> I haven’t looked into it much yet, but wanted to drop you both a note before I forget.  While giving the <omitted> training this afternoon, <they> were encountering quite a few “random” autotest fails.  Strangely enough, every one of the autotests that were failing were “failure autotests” (i.e., ones with “_err” in the filename).  Not every one did it and they weren’t very consistent in their failure.  The ones that failed started as exceptions, but after getting my copy of MSYS/MinGW to them, they are now just errors (with the 127 exit code error).  I was at a loss after we double checked all of their paths and such.  The fact that it was just a few “_err” autotests was quite odd too.
> 
> The MSYS is the same, so far as we could tell.  They initially had a potentially newer version of MinGW, or maybe something odd in their paths somewhere (I didn’t see anything that looked out of place).  We copied my whole MinGW/MSYS folder over and tried it again with identical results.  I thought about trying to go through the directions again and setting up MSYS/MinGW again, just to see if I can replicate it with a new version or if there is anything in the directions that I might have done different.  Or just updating MinGW and see if that does anything.  The fact that it is basically only appearing on “err” tests and seems to be associated with the exit code does seem to suggest something compiler-related.

The randomness of this problem makes it difficult to track down, so we should track if this pops up in other instances.

**Comment by dchassin** [comment] 2017-02-14 18:33
This is reminiscent of some problems I was having with my Eclipse/MSYS setup on Windows 10. I never did resolve the issue and Frank was not able to reproduce it on his Windows 10 system.

**Comment by ftuffner** [comment] 2020-08-26 16:36
Likely a duplicate of #1104, so closing - track on that ticket.

**Closed by ftuffner** 2020-08-26 16:36 UTC
Labels: bug
