### ISSUE TITLE
MacOS and Ubuntu Linux optimized release builds segfault on completion

### ISSUE THREAD

**Issue by ftuffner** [gridlab-d/gridlab-d#1193] opened 2019-09-27 17:01 UTC
MacOS and Ubuntu Linux optimized release builds segfault on completion

Text:
- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------
Building versions of GridLAB-D based on /develop and master (4.1) seem to have issues with optimization turned on and GridLAB-D exiting.  On MacOS builds (High Sierra - Homebrew GCC 8.2.0 and Homebrew GCC 9) and Ubuntu 19.04 builds (GCC 8.3.0), if optimization is set above 0 (so O1 or O2), GridLAB-D produces a segmentation fault on exit.  At O0 (no optimization), no segfault occurs.  No segfaults appear to occur under Windows MSYS2 builds (GCC 9.1.0) - that build exits fine, even at O2 optimization.

On MacOS and Ubuntu, the GLM appears to complete, and a select examination of autotests indicates they still are getting correct answers, they just fail on exit (so the validate procedure fails, due to segfaults at the end)

This only appears to happen when GridLAB-D runs a GLM.  With a --version or just running it empty (to get the webpage to open), no segfault appears.

## Please describe what was the cause of the issue?
Running GridLAB-D with a GLM file seems to produce it. 

## Please provide the steps to reproduce.
Run GridLAB-D with a GLM file.  It seems to occur 100% of the time on an optimized build.

## Please provide the exact error/warning/failure message printed on the console.
Ubuntu Linux - "Segmentation fault (core dumped)"
MacOS - "Segmentation fault: 11"

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by eberleim** [comment] 2019-11-07 19:57
Duplicate of #1167

**Closed** 2020-02-06 23:37 UTC
Labels: bug
