### ISSUE TITLE
issue in installing gridlabd and how to use its server mode to transfer data from gridlabd to other through port or client server request. by direct executing in terminal

### ISSUE THREAD

**Issue by karuneshm95** [gridlab-d/gridlab-d#1316] opened 2021-12-02 10:30 UTC
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [ ] I have not found an open issue describing the same problem.
- [ ] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [ ] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment] 2021-12-09 19:27
This issue could use some detail.  What issue is there installing?  Please fill out the form for the initial issue.

Regarding server mode, the documentation is at http://gridlab-d.shoutwiki.com/wiki/Realtime_server.  It is a largely unused, and nearly deprecated mode.  Depending on what you are trying to do, using the HELICS cosimulation framework may be a better option.

**Comment by ftuffner** [comment] 2021-12-09 19:29
Assuming this is a duplicate of #1317 - closing

**Closed by ftuffner** 2021-12-09 19:29 UTC
